package yuma140902.mcmods.industrial_essentials;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import yuma140902.mcmods.industrial_essentials.config.ModConfigCore;
import yuma140902.mcmods.industrial_essentials.modules.Modules;
import yuma140902.mcmods.industrial_essentials.proxy.CommonProxy;
import yuma140902.mcmods.yumalib.YumaLib;
import yuma140902.mcmods.yumalib.YumaLibApi;
import yuma140902.mcmods.yumalib.updatecheck.IUpdateChecker;
import yuma140902.mcmods.yumalib.updatecheck.UpdateChecker;

@Mod(modid = IndustrialEssentials.MOD_ID, name = IndustrialEssentials.MOD_NAME, 
			version = IndustrialEssentials.MOD_VERSION, useMetadata = true, 
			guiFactory = IndustrialEssentialsStat.MOD_CONFIG_GUI_FACTORY,
			dependencies = "after:" + YumaLib.MOD_ID + "@[0.0.0,1.0.0)"
		)
public class IndustrialEssentials {
	@Mod.Metadata
	public static ModMetadata modMetadata;
	
	@Mod.Instance
	public static IndustrialEssentials INSTANCE;
	
	@SidedProxy(clientSide = IndustrialEssentialsStat.PROXY_CLIENT, serverSide = IndustrialEssentialsStat.PROXY_SERVER)
	public static CommonProxy proxy;
	
	
	public static final String MOD_ID = "industrial_essentials";
	public static final String MOD_NAME = "IndustrialEssentials";
	public static final String MOD_TEXTURE_DOMAIN = "industrial_ess";
	public static final String MOD_UNLOCALIZED_ENTRY_DOMAIN = "industrial_ess";
	public static final String MINECRAFT_VERSION = "1.7.10";
	public static final String MOD_VERSION = "0.0.0";
	public static final String MOD_VERSIONS_TSV_URL = "https://raw.githubusercontent.com/yuma140902/UpdateJSON_Forge/master/UpToDateModVersions.tsv";
	public static final Logger LOGGER = LogManager.getLogger(MOD_NAME);
	
	private void loadModMetadata(ModMetadata modMetadata) {
		modMetadata.modId = MOD_ID;
		modMetadata.name = MOD_NAME;
		modMetadata.version = MOD_VERSION;
		modMetadata.authorList.add("yuma140902");
		modMetadata.description = "Adds essential machines, tools, etc";
		modMetadata.url = "https://minecraft.curseforge.com/projects/industrial_essentials";
		modMetadata.autogenerated = false;
	}
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		loadModMetadata(modMetadata);
		ModConfigCore.loadConfig(event);
		IUpdateChecker updateChecker = new UpdateChecker(MOD_NAME, MOD_VERSIONS_TSV_URL, ModConfigCore.Stats.updateChannel(), MOD_VERSION, modMetadata.url, ModConfigCore.Stats.isDebugMode());
		LOGGER.info("preInit");
		try {
			updateChecker.checkForUpdates();
		}
		catch (Exception e) {
			e.printStackTrace();
		}
		LOGGER.info(updateChecker.hasNewVersionAvailable() ? "There is a new version available. - v" + updateChecker.getAvailableNewVersion() + ". Visit " + updateChecker.getNewVersionUrl() : "UpToDateMod is now up-to-date.");
		
		YumaLibApi.registerUpdateChecker(updateChecker);
		
		Modules.initModules();
		Modules.onPreInit(event);
		
		//ModBlocks.register();
		//ModItems.register();
		
		//proxy.registerTileEntities();
		//ModGuis.register();
		
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event) {
		LOGGER.info("init");
		
		Modules.onInit(event);
		
		//Recipes.register();
		
		//proxy.registerEntities();
		
		//WorldGenerators.register();
		
		proxy.registerEventHandlers();
		
		//Plugins.tweakMods();
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		LOGGER.info("postInit");
		
		Modules.onPostInit(event);
		
		//Plugins.tweakModsPost();
		//Plugins.logPluginStats();
	}
}
